SELECT A.WRITER_ID, B.NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소', CONCAT((SUBSTR(B.TLNO, 1, 3)), '-', SUBSTR(B.TLNO, 4, 4), '-', SUBSTR(B.TLNO, 8))
AS '전화번호' FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID HAVING COUNT(WRITER_ID) >= 3
ORDER BY B.USER_ID DESC;
